<?php

// Framework configuration globals; applied across the entire framework

define ("APPLICATION_DIRECTORY", ENVIRONMENT_PATH . DIRECTORY_SEPARATOR . "app");
define ("APP_CONFIG_DIRECTORY", APPLICATION_DIRECTORY . DIRECTORY_SEPARATOR . "config");
define ("COMPONENT_DIRECTORY", ENVIRONMENT_PATH . DIRECTORY_SEPARATOR . "component");
define ("INCLUDE_DIRECTORY", ENVIRONMENT_PATH . DIRECTORY_SEPARATOR . "include");
define ("SERVICE_DIRECTORY", ENVIRONMENT_PATH . DIRECTORY_SEPARATOR . "service");
define ("WEB_DIRECTORY", ENVIRONMENT_PATH . DIRECTORY_SEPARATOR . "web");

define ("FILE_EXTENSION", ".php");

?>
